routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [App\Http\Controllers\Catering\FrontController::class, 'index'])->name('front.index');
Route::get('/product', [App\Http\Controllers\Catering\FrontController::class, 'product'])->name('front.product');
Route::get('/faq', [App\Http\Controllers\Catering\FrontController::class, 'getFaq'])->name('front.faq');
Route::get('/contact', [App\Http\Controllers\Catering\FrontController::class, 'getContact'])->name('front.contact');
Route::post('/sendemail', [App\Http\Controllers\Catering\FrontController::class, 'sendEmail'])->name('front.post_contact');
// Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
// Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'index'])->name('customer.profile');



Route::group(['prefix' => 'member', 'namespace' => 'catering'], function() {
    Route::get('/register', [App\Http\Controllers\Catering\RegisterController::class, 'registerForm'])->name('customer.register');
    Route::post('/register', [App\Http\Controllers\Catering\RegisterController::class, 'register'])->name('customer.post_register');
    Route::get('/login', [App\Http\Controllers\Catering\LoginController::class, 'loginForm'])->name('customer.login');
    Route::post('/login', [App\Http\Controllers\Catering\LoginController::class, 'login'])->name('customer.post_login');
    Route::get('/verify/{token}', [App\Http\Controllers\Catering\FrontController::class, 'verifyCustomerRegistration'])->name('customer.verify');
});

Route::group(['middleware' => 'customer'], function() {
    // product
    Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
    // cart
    Route::get('/cart', [App\Http\Controllers\Catering\CartController::class, 'listCart'])->name('front.list_cart');
    Route::post('/cart', [App\Http\Controllers\Catering\CartController::class, 'addToCart'])->name('front.add_cart');
    Route::post('/cart/update', [App\Http\Controllers\Catering\CartController::class, 'updateCart'])->name('front.update_cart');
    Route::get('/cart/{id}/delete', [App\Http\Controllers\Catering\CartController::class, 'deleteCart'])->name('front.delete_cart');
    // checkout
    Route::get('/checkout', [App\Http\Controllers\Catering\CartController::class, 'checkout'])->name('front.checkout');
    Route::get('/checkout/{invoice}', [App\Http\Controllers\Catering\CartController::class, 'checkoutFinish'])->name('front.finish_checkout');
    Route::post('/checkout', [App\Http\Controllers\Catering\CartController::class, 'processCheckout'])->name('front.store_checkout');
    // profile
    Route::get('/dashboard', [App\Http\Controllers\Catering\LoginController::class, 'dashboard'])->name('customer.dashboard');
    Route::get('/logout', [App\Http\Controllers\Catering\LoginController::class, 'logout'])->name('customer.logout');
    Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'myProfile'])->name('customer.profile');
    Route::put('/profile/{id}', [App\Http\Controllers\Catering\ProfileController::class, 'updateMyProfile'])->name('customer.update_profile');
    Route::get('/order', [App\Http\Controllers\Catering\ProfileController::class, 'myOrder'])->name('customer.order');
    // payment
    Route::post('/paymentproses/{id_order}', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentProses'])->name('customer.payment_proses');
    Route::post('/paymentconfirm', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentConfirm'])->name('customer.payment_confirm');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function(){
    // Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::resource();
    Route::resource('category', 'App\Http\Controllers\CategoryController');
    Route::resource('order', 'App\Http\Controllers\OrderController');
    Route::resource('customer', 'App\Http\Controllers\CustomerController');
    Route::resource('product', 'App\Http\Controllers\ProductController');
    Route::resource('payment', 'App\Http\Controllers\PaymentController');
    Route::get('/signout', [App\Http\Controllers\HomeController::class, 'signout'])->name('signout');
});

Route::get('/tes', function(){
    $active = 'p';
    return view('catering.my_order', compact('active'));
});

app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $table = 'payments';

    public function order(){
        return $this->belongsTo(Order::class);
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Payment;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PaymentController extends Controller
{
    public function index(){
        $active = 'Payment';
        $payments = Payment::orderBy('created_at', 'DESC')->paginate(5);

        return view('payments.index', compact('payments', 'active'));
    }

    public function edit(Request $req, $id){
        
        $active = 'Payment';
        $payment = Payment::find($id);
        $total = collect($payment->order->details)->sum(function($q){
            return $q->price * $q->qty;
        });

        return view('payments.confirm', compact('active', 'payment', 'total'));
    }
}

resources/views/payments/confirm.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin | Payment</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            @if (session('success'))
            <div class="success alert alert-success">
                {{session('success')}}
            </div>
            @endif
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header bg-dark">
                            <h4 class="card-title">Payment Confirm</h4>
                        </div>
                        <div class="card-body p-3">
                            <form action="{{route('customer.payment_confirm')}}" method="POST">
                                @csrf
                                <input type="hidden" name="payment_id" value="{{$payment->id}}">
                                <div class="mb-3">
                                    <label class="form-label">Invoice</label>
                                    <input type="text" class="form-control" value="{{$payment->order->invoice}}"
                                        readonly>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Name Transfer</label>
                                    <input type="text" class="form-control" value="{{$payment->name_transfer}}"
                                        readonly>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Name Bank Transfer</label>
                                    <input type="text" class="form-control" value="{{$payment->name_bank_transfer}}"
                                        readonly>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Transfer Date</label>
                                    <input type="text" class="form-control" value="{{$payment->transfer_date}}"
                                        readonly>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Jumlah</label>
                                    <input type="text" class="form-control" value="IDR. {{$payment->amount}}" readonly>
                                </div>
                                <div class="mb">
                                    <label class="form-label">Proof</label>
                                </div>
                                <div class="images my-3 text-center">
                                    <img src="{{asset('storage/images/payment/'.$payment->image_transfer)}}" alt=""
                                        width="400">
                                </div>
                                <div class="mb-3">
                                    @if ($payment->status == 0)
                                    <button class="btn btn-primary w-100">Konfirmasi Pembayaran</button>
                                    @else
                                    <input type="button" class="btn btn-secondary w-100" value="Konfirmasi Pembayaran"
                                        readonly>
                                    @endif
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                {{-- preview barang --}}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header bg-dark">
                            <h4 class="card-title">Preview Order</h4>
                        </div>
                        <div class="card-body">
                            <div class="">
                                <ul class="list-inline">
                                    <li class="text-bold"><small
                                            class="text-black-50">Invoice</small><br>{{$payment->order->invoice}}
                                    </li>
                                    <li class="text-bold"><small class="text-black-50">Nama
                                            Pemesan</small><br>{{$payment->order->customer_name}}
                                    </li>
                                    <li class="text-bold"><small
                                            class="text-black-50">No.Hp</small><br>{{$payment->order->customer_phone}}
                                    </li>
                                    <li class="text-bold"><small
                                            class="text-black-50">Alamat</small><br>{{$payment->order->customer_address}}
                                    </li>
                                </ul>
                                <hr>
                                <h5>Pesanan</h5>
                                @foreach ($payment->order->details as $item)
                                <div class="d-flex justify-content-between">
                                    <p class="my-1">&#8226;
                                        {{Str::limit($item->product->name, 20)}}
                                        <span class="badge bg-warning">{{$item->qty}}</span>
                                    </p>
                                    <p class="my-1 text-bold">IDR.{{number_format($item->price)}}</p>
                                </div>
                                @endforeach
                                <hr>
                                <div class="d-flex justify-content-end">
                                    <span class="text-bold">IDR. {{number_format($total)}}</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-body {{($payment->status == 1) ? 'bg-success' : 'bg-danger' }} text-center">
                            <h5 class="fw-bold">{{($payment->status == 1) ? 'Di Bayar' : 'Belum Di Bayar'}}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/payments/index.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin | Payment</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header bg-dark">
                            <h4 class="card-title">List Payment</h4>
                        </div>
                        <div class="card-body p-0">
                            <table class="table table-dark table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Invoice</th>
                                        <th scope="col">Name</th>
                                        <th scope="col" class="text-center">Transfer Date</th>
                                        <th scope="col" class="text-center">Amount</th>
                                        <th scope="col" class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($payments as $payment)
                                    <tr>
                                        <td>{{$payment->order->invoice}}</td>
                                        <td>{{$payment->name_transfer}} <i
                                                class="{{($payment->status == 1) ? 'fas fa-check-circle text-success' : 'fas fa-times-circle text-danger'}}"></i>
                                        </td>
                                        <td class="text-center">{{$payment->transfer_date}}</td>
                                        <td class="text-center">IDR. {{number_format($payment->amount)}}</td>
                                        <td class="text-center">
                                            <a href="{{route('payment.edit', $payment->id)}}"
                                                class="btn btn-warning btn-sm">Lihat</a>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="5">Tidak Ada Pembayaran</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection