routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [App\Http\Controllers\Catering\FrontController::class, 'index'])->name('front.index');
Route::get('/product', [App\Http\Controllers\Catering\FrontController::class, 'product'])->name('front.product');
Route::get('/faq', [App\Http\Controllers\Catering\FrontController::class, 'getFaq'])->name('front.faq');
Route::get('/contact', [App\Http\Controllers\Catering\FrontController::class, 'getContact'])->name('front.contact');
Route::post('/sendemail', [App\Http\Controllers\Catering\FrontController::class, 'sendEmail'])->name('front.post_contact');
// Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
// Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'index'])->name('customer.profile');



Route::group(['prefix' => 'member', 'namespace' => 'catering'], function() {
    Route::get('/register', [App\Http\Controllers\Catering\RegisterController::class, 'registerForm'])->name('customer.register');
    Route::post('/register', [App\Http\Controllers\Catering\RegisterController::class, 'register'])->name('customer.post_register');
    Route::get('/login', [App\Http\Controllers\Catering\LoginController::class, 'loginForm'])->name('customer.login');
    Route::post('/login', [App\Http\Controllers\Catering\LoginController::class, 'login'])->name('customer.post_login');
    Route::get('/verify/{token}', [App\Http\Controllers\Catering\FrontController::class, 'verifyCustomerRegistration'])->name('customer.verify');
});

Route::group(['middleware' => 'customer'], function() {
    // product
    Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
    // cart
    Route::get('/cart', [App\Http\Controllers\Catering\CartController::class, 'listCart'])->name('front.list_cart');
    Route::post('/cart', [App\Http\Controllers\Catering\CartController::class, 'addToCart'])->name('front.add_cart');
    Route::post('/cart/update', [App\Http\Controllers\Catering\CartController::class, 'updateCart'])->name('front.update_cart');
    Route::get('/cart/{id}/delete', [App\Http\Controllers\Catering\CartController::class, 'deleteCart'])->name('front.delete_cart');
    // checkout
    Route::get('/checkout', [App\Http\Controllers\Catering\CartController::class, 'checkout'])->name('front.checkout');
    Route::get('/checkout/{invoice}', [App\Http\Controllers\Catering\CartController::class, 'checkoutFinish'])->name('front.finish_checkout');
    Route::post('/checkout', [App\Http\Controllers\Catering\CartController::class, 'processCheckout'])->name('front.store_checkout');
    // profile
    Route::get('/dashboard', [App\Http\Controllers\Catering\LoginController::class, 'dashboard'])->name('customer.dashboard');
    Route::get('/logout', [App\Http\Controllers\Catering\LoginController::class, 'logout'])->name('customer.logout');
    Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'myProfile'])->name('customer.profile');
    Route::put('/profile/{id}', [App\Http\Controllers\Catering\ProfileController::class, 'updateMyProfile'])->name('customer.update_profile');
    Route::get('/order', [App\Http\Controllers\Catering\ProfileController::class, 'myOrder'])->name('customer.order');
    // payment
    Route::post('/paymentproses/{id_order}', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentProses'])->name('customer.payment_proses');
    Route::post('/paymentconfirm', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentConfirm'])->name('customer.payment_confirm');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function(){
    // Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::resource();
    Route::resource('category', 'App\Http\Controllers\CategoryController');
    Route::resource('order', 'App\Http\Controllers\OrderController');
    Route::resource('customer', 'App\Http\Controllers\CustomerController');
    Route::resource('product', 'App\Http\Controllers\ProductController');
    Route::resource('payment', 'App\Http\Controllers\PaymentController');
    Route::get('/signout', [App\Http\Controllers\HomeController::class, 'signout'])->name('signout');
});

Route::get('/tes', function(){
    $active = 'p';
    return view('catering.my_order', compact('active'));
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'status'];

    // Mutator
    public function setSlugAttribute($value){
        $this->attributes['slug'] = Str::slug($value);
    }

    // Accessor
    public function getNameAttribute($value){
        return ucfirst($value);
    }

    public function product()
    {
        //JENIS RELASINYA ADALAH ONE TO MANY, YANG BERARTI KATEGORI INI BISA DIGUNAKAN OLEH BANYAK PRODUK
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $active = 'Category';
        $category = Category::orderBy('created_at', 'DESC')->paginate(10);

        return view('categories.index', compact('category', 'active'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    //  insert item category to database.
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50|unique:categories',
        ]);
        
        $request->request->add(['slug' => $request->name]);
        
        Category::create([
            'name' => $request->name,
            'slug' => $request->slug,
        ]);

        return redirect(route('category.index'))->with('success', 'Kategori baru ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        $active = 'Category';
        return view('categories.edit', compact('category', 'active'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50|unique:categories,name,' . $id,
            'status' => 'required',
        ]);

        $category = Category::find($id);

        $category->update([
            'name' => $request->name,
            'status' => $request->status,
        ]);

        return redirect(route('category.index'))->with('success', 'Kategory berhasil dirubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $category = Category::find($id);

        $category = Category::withCount(['product'])->find($id);

        if($category->product_count == 0){
            $category->delete();
            return redirect(route('category.index'))->with('success', 'Kategori berhasil dihapus');
        }

        return redirect(route('category.index'))->with('error', 'Kategori sedang digunakan');
    }
}

resources/views/categories/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Admin | Edit Category</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">     
                
              <div class="col px-4">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit Category</h4>
                    </div>
                    <div class="card-body">
                        
                        <form action="{{route('category.update', $category->id)}}" method="POST">
                          @csrf
                          @method('PUT')
                            <div class="form-group">
                              <label for="name">Nama Kategori</label>
                              <input type="text" name="name" class="form-control" value="{{ $category->name}}">
                              @error('name')
                                  <small class="text-danger">{{$message}}</small>
                              @enderror
                            </div>
                            <div class="form-group">
                              <label for="inputState">Status</label>
                              <select id="inputState" name="status" class="form-control">
                                <option {{($category->status === 1) ? 'selected' : null}} value='1'>Aktif</option>
                                <option {{($category->status === 0) ? 'selected' : null}} value='0'>Tidak Aktif</option>
                              </select>
                            </div>
                            <div class="form-group">
                              <button type="submit" class="btn btn-primary float-right">Update Category</button>
                            </div>
                        </form>
                        
                    </div>
                </div>
              </div>

            </div>
        </div>
    </div>
</main>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Admin | Category</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
        
                <!-- BAGIAN INI AKAN MENG-HANDLE FORM INPUT NEW CATEGORY  -->
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Kategori Baru</h4>
                        </div>
                        <div class="card-body">
                            
                            <form action="{{ route('category.store') }}" method="post">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Nama Kategori</label>
                                    <input type="text" name="name" class="form-control">
                                    @error('name')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-sm">Tambah</button>
                                </div>
                            </form>
                            
                        </div>
                    </div>
                </div>
                <!-- BAGIAN INI AKAN MENG-HANDLE FORM INPUT NEW CATEGORY  -->
                
                <!-- BAGIAN INI AKAN MENG-HANDLE TABLE LIST CATEGORY  -->
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List Kategori</h4>
                        </div>
                        <div class="card-body">
                            <!-- KETIKA ADA SESSION SUCCESS  -->
                            @if (session('success'))
                                <!-- MAKA TAMPILKAN ALERT SUCCESS -->
                                <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            <!-- KETIKA ADA SESSION ERROR  -->
                            @if (session('error'))
                                <!-- MAKA TAMPILKAN ALERT DANGER -->
                                <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif

                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 80px">No.</th>
                                            <th>Kategori</th>
                                            <th>Status</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!-- LOOPING DATA KATEGORI SESUAI JUMLAH DATA YANG ADA DI VARIABLE $CATEGORY -->
                                        @forelse ($category as $val)
                                        <tr>
                                                <td>{{$loop->iteration}}. </td>
                                                <td><strong>{{ $val->name }}</strong></td>
                                                <td>
                                                    <span class="badge badge-{{($val->status===1) ? 'success' : 'secondary'}}">
                                                        {{($val->status === 1) ? 'Aktif' : 'Tidak Aktif'}}
                                                    </span>
                                                </td>
                                                <td>
                                                    <!-- FORM ACTION UNTUK METHOD DELETE -->
                                                    <form action="{{ route('category.destroy', $val->id) }}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <a href="{{ route('category.edit', $val->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                                        <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                                                        </form>
                                                </td>
                                        </tr>
                                        <!-- JIKA DATA CATEGORY KOSONG, MAKA AKAN DIRENDER KOLOM DIBAWAH INI  -->
                                        @empty
                                        <tr>
                                            <td colspan="5" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                            <!-- FUNGSI INI AKAN SECARA OTOMATIS MEN-GENERATE TOMBOL PAGINATION  -->
                            {!! $category->links() !!}
                        </div>
                    </div>
                </div>
                <!-- BAGIAN INI AKAN MENG-HANDLE TABLE LIST CATEGORY  -->
                
            </div>
        </div>
    </div>
</main>
@endsection