routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [App\Http\Controllers\Catering\FrontController::class, 'index'])->name('front.index');
Route::get('/product', [App\Http\Controllers\Catering\FrontController::class, 'product'])->name('front.product');
Route::get('/faq', [App\Http\Controllers\Catering\FrontController::class, 'getFaq'])->name('front.faq');
Route::get('/contact', [App\Http\Controllers\Catering\FrontController::class, 'getContact'])->name('front.contact');
Route::post('/sendemail', [App\Http\Controllers\Catering\FrontController::class, 'sendEmail'])->name('front.post_contact');
// Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
// Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'index'])->name('customer.profile');



Route::group(['prefix' => 'member', 'namespace' => 'catering'], function() {
    Route::get('/register', [App\Http\Controllers\Catering\RegisterController::class, 'registerForm'])->name('customer.register');
    Route::post('/register', [App\Http\Controllers\Catering\RegisterController::class, 'register'])->name('customer.post_register');
    Route::get('/login', [App\Http\Controllers\Catering\LoginController::class, 'loginForm'])->name('customer.login');
    Route::post('/login', [App\Http\Controllers\Catering\LoginController::class, 'login'])->name('customer.post_login');
    Route::get('/verify/{token}', [App\Http\Controllers\Catering\FrontController::class, 'verifyCustomerRegistration'])->name('customer.verify');
});

Route::group(['middleware' => 'customer'], function() {
    // product
    Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
    // cart
    Route::get('/cart', [App\Http\Controllers\Catering\CartController::class, 'listCart'])->name('front.list_cart');
    Route::post('/cart', [App\Http\Controllers\Catering\CartController::class, 'addToCart'])->name('front.add_cart');
    Route::post('/cart/update', [App\Http\Controllers\Catering\CartController::class, 'updateCart'])->name('front.update_cart');
    Route::get('/cart/{id}/delete', [App\Http\Controllers\Catering\CartController::class, 'deleteCart'])->name('front.delete_cart');
    // checkout
    Route::get('/checkout', [App\Http\Controllers\Catering\CartController::class, 'checkout'])->name('front.checkout');
    Route::get('/checkout/{invoice}', [App\Http\Controllers\Catering\CartController::class, 'checkoutFinish'])->name('front.finish_checkout');
    Route::post('/checkout', [App\Http\Controllers\Catering\CartController::class, 'processCheckout'])->name('front.store_checkout');
    // profile
    Route::get('/dashboard', [App\Http\Controllers\Catering\LoginController::class, 'dashboard'])->name('customer.dashboard');
    Route::get('/logout', [App\Http\Controllers\Catering\LoginController::class, 'logout'])->name('customer.logout');
    Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'myProfile'])->name('customer.profile');
    Route::put('/profile/{id}', [App\Http\Controllers\Catering\ProfileController::class, 'updateMyProfile'])->name('customer.update_profile');
    Route::get('/order', [App\Http\Controllers\Catering\ProfileController::class, 'myOrder'])->name('customer.order');
    // payment
    Route::post('/paymentproses/{id_order}', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentProses'])->name('customer.payment_proses');
    Route::post('/paymentconfirm', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentConfirm'])->name('customer.payment_confirm');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function(){
    // Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::resource();
    Route::resource('category', 'App\Http\Controllers\CategoryController');
    Route::resource('order', 'App\Http\Controllers\OrderController');
    Route::resource('customer', 'App\Http\Controllers\CustomerController');
    Route::resource('product', 'App\Http\Controllers\ProductController');
    Route::resource('payment', 'App\Http\Controllers\PaymentController');
    Route::get('/signout', [App\Http\Controllers\HomeController::class, 'signout'])->name('signout');
});

Route::get('/tes', function(){
    $active = 'p';
    return view('catering.my_order', compact('active'));
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use Illuminate\Notifications\Notifiable;

class Customer extends Authenticatable
{
    use Notifiable;

    protected $guarded = [];

    public function setPasswordAttribute($value){
        $this->attributes['password'] = Hash::make($value);
    }
    
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Customer;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::orderBy('created_at', 'DESC')->get();
        $active = 'Customer';

        return view('customer.index', compact('active', 'customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer = Customer::find($id);
        $active = 'Customer';
        return view('customer.edit', compact('active', 'customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $status = $request->only('status');

        $customer = Customer::find($id);
        $customer->status = $status['status'];
        $customer->save();

        return redirect(route('customer.index'))->with('success', 'Customer status berhasil diupdate');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Customer/edit.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin | Edit Customer</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mx-3">
                        <div class="card-header">
                            <h4 class="card-title">Customer</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{route('customer.update', $customer->id)}}" method="POST">
                                @csrf
                                @method('PUT')
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Status</label>
                                    <div class="col-sm-10">
                                        <select class="form-control" name="status">
                                            <option value="1" {{($customer->status === 1) ? 'selected' : ''}}>Aktif
                                            </option>
                                            <option value="0" {{($customer->status === 0) ? 'selected' : ''}}>Tidak
                                                Aktif
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Full Name</label>
                                    <div class="col-sm-10">
                                        <input type="text" value="{{$customer->name}}" class="form-control input__form"
                                            readonly>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Email Address</label>
                                    <div class="col-sm-10">
                                        <input type="email" value="{{$customer->email}}" class="form-control" readonly>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Phone Number</label>
                                    <div class="col-sm-10 input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">+62</div>
                                        </div>
                                        <input type="number" class="form-control" value="{{$customer->phone_number}}"
                                            readonly>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label">Address</label>
                                    <div class="col-sm-10">
                                        <textarea class="form-control" rows="8"
                                            readonly>{{$customer->address}}</textarea>
                                    </div>
                                </div>
                                <div class="row justify-content-end px-2">
                                    <button type="submit" class="btn btn-primary w-25">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/Customer/index.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin | Customer</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    @if (session('success'))
                    <div class="alert alert-success">
                        {{session('success')}}
                    </div>
                    @endif
                    <div class="card">
                        <div class="card-header bg-dark">
                            <h4 class="card-title">Customer</h4>
                        </div>
                        <div class="card-body p-0">
                            <table class="table table-hover table-dark">
                                <thead>
                                    <tr>
                                        <th scope="col">No.</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($customers as $customer)
                                    <tr>
                                        <th scope="row">{{$loop->iteration}}.</th>
                                        <td>{{$customer->name}}</td>
                                        <td>{{$customer->email}}</td>
                                        <td>
                                            @if ($customer->status == 0)
                                            <span class="badge badge-secondary">Tidak Aktif</span>
                                            @else
                                            <span class="badge badge-success">Aktif</span>
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{route('customer.edit', $customer->id)}}"
                                                class="btn btn-sm btn-warning">Edit</a>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection