routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [App\Http\Controllers\Catering\FrontController::class, 'index'])->name('front.index');
Route::get('/product', [App\Http\Controllers\Catering\FrontController::class, 'product'])->name('front.product');
Route::get('/faq', [App\Http\Controllers\Catering\FrontController::class, 'getFaq'])->name('front.faq');
Route::get('/contact', [App\Http\Controllers\Catering\FrontController::class, 'getContact'])->name('front.contact');
Route::post('/sendemail', [App\Http\Controllers\Catering\FrontController::class, 'sendEmail'])->name('front.post_contact');
// Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
// Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'index'])->name('customer.profile');



Route::group(['prefix' => 'member', 'namespace' => 'catering'], function() {
    Route::get('/register', [App\Http\Controllers\Catering\RegisterController::class, 'registerForm'])->name('customer.register');
    Route::post('/register', [App\Http\Controllers\Catering\RegisterController::class, 'register'])->name('customer.post_register');
    Route::get('/login', [App\Http\Controllers\Catering\LoginController::class, 'loginForm'])->name('customer.login');
    Route::post('/login', [App\Http\Controllers\Catering\LoginController::class, 'login'])->name('customer.post_login');
    Route::get('/verify/{token}', [App\Http\Controllers\Catering\FrontController::class, 'verifyCustomerRegistration'])->name('customer.verify');
});

Route::group(['middleware' => 'customer'], function() {
    // product
    Route::get('/product/{slug}', [App\Http\Controllers\Catering\FrontController::class, 'show'])->name('front.show_product');
    // cart
    Route::get('/cart', [App\Http\Controllers\Catering\CartController::class, 'listCart'])->name('front.list_cart');
    Route::post('/cart', [App\Http\Controllers\Catering\CartController::class, 'addToCart'])->name('front.add_cart');
    Route::post('/cart/update', [App\Http\Controllers\Catering\CartController::class, 'updateCart'])->name('front.update_cart');
    Route::get('/cart/{id}/delete', [App\Http\Controllers\Catering\CartController::class, 'deleteCart'])->name('front.delete_cart');
    // checkout
    Route::get('/checkout', [App\Http\Controllers\Catering\CartController::class, 'checkout'])->name('front.checkout');
    Route::get('/checkout/{invoice}', [App\Http\Controllers\Catering\CartController::class, 'checkoutFinish'])->name('front.finish_checkout');
    Route::post('/checkout', [App\Http\Controllers\Catering\CartController::class, 'processCheckout'])->name('front.store_checkout');
    // profile
    Route::get('/dashboard', [App\Http\Controllers\Catering\LoginController::class, 'dashboard'])->name('customer.dashboard');
    Route::get('/logout', [App\Http\Controllers\Catering\LoginController::class, 'logout'])->name('customer.logout');
    Route::get('/profile', [App\Http\Controllers\Catering\ProfileController::class, 'myProfile'])->name('customer.profile');
    Route::put('/profile/{id}', [App\Http\Controllers\Catering\ProfileController::class, 'updateMyProfile'])->name('customer.update_profile');
    Route::get('/order', [App\Http\Controllers\Catering\ProfileController::class, 'myOrder'])->name('customer.order');
    // payment
    Route::post('/paymentproses/{id_order}', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentProses'])->name('customer.payment_proses');
    Route::post('/paymentconfirm', [App\Http\Controllers\Catering\PaymentControlelr::class, 'paymentConfirm'])->name('customer.payment_confirm');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function(){
    // Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::resource();
    Route::resource('category', 'App\Http\Controllers\CategoryController');
    Route::resource('order', 'App\Http\Controllers\OrderController');
    Route::resource('customer', 'App\Http\Controllers\CustomerController');
    Route::resource('product', 'App\Http\Controllers\ProductController');
    Route::resource('payment', 'App\Http\Controllers\PaymentController');
    Route::get('/signout', [App\Http\Controllers\HomeController::class, 'signout'])->name('signout');
});

Route::get('/tes', function(){
    $active = 'p';
    return view('catering.my_order', compact('active'));
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    //INI ADALAH ACCESSOR, JADI KITA MEMBUAT KOLOM BARU BERNAMA STATUS_LABEL
    //KOLOM TERSEBUT DIHASILKAN OLEH ACCESSOR, MESKIPUN FIELD TERSEBUT TIDAK ADA DITABLE PRODUCTS
    //AKAN TETAPI AKAN DISERTAKAN PADA HASIL QUERY
    public function getStatusLabelAttribute()
    {
        //ADAPUN VALUENYA AKAN MENCETAK HTML BERDASARKAN VALUE DARI FIELD STATUS
        if ($this->status == 0) {
            return '<span class="badge badge-secondary">Draft</span>';
        }
        return '<span class="badge badge-success">Aktif</span>';
    }

    //FUNGSI YANG MENG-HANDLE RELASI KE TABLE CATEGORY
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    // Mutators
    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug($value); 
    }

    public function order(){
        return $this->belongsToMany(Order::class, 'order_details');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Product::with(['category'])->orderBy('created_at', 'DESC');
        if(request()->q != ''){
            $product = $product->where('name', 'LIKE', '%' . request()->q . '%');
        }
        $product = $product->paginate(5);
        $active = "Product";

        return view('products.index', compact('product', 'active'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::where('status', 1)->orderBy('name', 'DESC')->get();
        $active = "Product";

        return view('products.create', compact('category', 'active'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //VALIDASI REQUESTNYA
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'description' => 'required',
            'category_id' => 'required|exists:categories,id', //CATEGORY_ID KITA CEK HARUS ADA DI TABLE CATEGORIES DENGAN FIELD ID
            'price' => 'required|integer',
            'image' => 'required | image | mimes:png,jpeg,jpg |max:2048', //GAMBAR DIVALIDASI HARUS BERTIPE PNG,JPG DAN JPEG
        ]);

        // upload image to storage
        $imageName = $this->uploadImage($request->image, null);

        //SETELAH FILE TERSEBUT DISIMPAN, KITA SIMPAN INFORMASI PRODUKNYA KEDALAM DATABASE
        Product::create([
            'name' => $request->name,
            'slug' => $request->name,
            'category_id' => $request->category_id,
            'description' => $request->description,
            'image' => $imageName, //PASTIKAN MENGGUNAKAN VARIABLE FILENAM YANG HANYA BERISI NAMA FILE SAJA (STRING)
            'price' => $request->price,
            'status' => $request->status,
        ]);
        
        
        return redirect(route('product.index'))->with(['success' => 'Produk Baru Ditambahkan']);
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $category = Category::where('status', 1)->orderBy('name', 'DESC')->get();
        $active = "Product";
        return view('products.edit', compact('active', 'product', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:100',
            'description' => 'required',
            'category_id' => 'required|exists:categories,id', //CATEGORY_ID KITA CEK HARUS ADA DI TABLE CATEGORIES DENGAN FIELD ID
            'price' => 'required|integer',
            'image' => 'nullable | image | mimes:png,jpeg,jpg |max:2048', //GAMBAR DIVALIDASI HARUS BERTIPE PNG,JPG DAN JPEG
        ]);

        $product = Product::find($id);
        
        $imageName = $this->uploadImage($request->image, $product->image);
        // dd($imageName);
        
        $product->update([
            'name' => $request->name,
            'description' => $request->description,
            'status' => $request->status,
            'category_id' => $request->category_id,
            'price' => $request->price,
            'image' => $imageName,
        ]);

        return redirect(route('product.index'))->with('success', 'Product berhasil diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);

        Storage::delete('/public/images/product/'.$product->image);

        $product->delete();

        return redirect(route('product.index'))->with('success', 'Product berhasil dihapus');
    }

    public function uploadImage($imgProduct, $imageDB){
        $imageName = $imageDB;
        if(!empty($imgProduct)){
            $imageName = md5(time() . '.' . $imgProduct->extension());

            Storage::putFileAs(
                'public/images/product',
                $imgProduct,
                $imageName,
            );

            if ($imageDB != null) {
                Storage::delete('/public/images/product/'.$imageDB);
            }
        }
        return $imageName;
    }
}

resources/views/products/create.blade.php
@extends('layouts.admin')

@section('title')
    <title>Admin | Add Product</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">Product</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn p-3">
          
          	<!-- TAMBAHKAN ENCTYPE="" KETIKA MENGIRIMKAN FILE PADA FORM -->
            <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data" >
                @csrf
                <div class="row">
                    <div class="col-md-8">
                        <div class="card" style="min-height: 525px">
                            <div class="card-header">
                                <h4 class="card-title">Tambah Produk</h4>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Nama Produk</label>
                                    <input type="text" name="name" class="form-control" value="{{ old('name') }}">
                                    @error('name')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="description">Deskripsi</label>
                                  
                                    <!-- TAMBAHKAN ID YANG NNTINYA DIGUNAKAN UTK MENGHUBUNGKAN DENGAN CKEDITOR -->
                                    <textarea name="description" id="description" rows="10" class="form-control">{{ old('description') }}</textarea>
                                    @error('description')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card" style="min-height: 525px">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select name="status" class="form-control">
                                        <option value="1" {{ old('status') == '1' ? 'selected':'' }}>Publish</option>
                                        <option value="0" {{ old('status') == '0' ? 'selected':'' }}>Draft</option>
                                    </select>
                                    <p class="text-danger">{{ $errors->first('status') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Kategori</label>
                                    
                                    <!-- DATA KATEGORI DIGUNAKAN DISINI, SEHINGGA SETIAP PRODUK USER BISA MEMILIH KATEGORINYA -->
                                    <select name="category_id" class="form-control">
                                        <option value="">Pilih</option>
                                        @foreach ($category as $row)
                                        <option value="{{ $row->id }}" {{ old('category_id') == $row->id ? 'selected':'' }}>{{ $row->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('category_id')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="price">Harga</label>
                                    <input type="number" name="price" class="form-control" value="{{ old('price') }}">
                                    @error('price')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                  <label for="image">Foto Produk</label>
                                  <div class="custom-file">
                                    <input type="file" name="image" class="custom-file-input" id="customFile">
                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                  </div>
                                  @error('image')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-sm">Tambah</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>
@endsection

<!-- PADA ADMIN LAYOUTS, TERDAPAT YIELD JS YANG BERARTI KITA BISA MEMBUAT SECTION JS UNTUK MENAMBAHKAN SCRIPT JS JIKA DIPERLUKAN -->
@section('js')
    <!-- LOAD CKEDITOR -->
    {{-- <script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
    <script>
        //TERAPKAN CKEDITOR PADA TEXTAREA DENGAN ID DESCRIPTION
        CKEDITOR.replace('description', {
          height: 150
        });
    </script> --}}
    <script type="application/javascript">
      $('input[type="file"]').change(function(e){
          var fileName = e.target.files[0].name;
          $('.custom-file-label').html(fileName);
      });
  </script> 
@endsection

resources/views/products/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Admin | Add Product</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn p-3">
          
          	<!-- TAMBAHKAN ENCTYPE="" KETIKA MENGIRIMKAN FILE PADA FORM -->
            <form action="{{ route('product.update', $product->id) }}" method="post" enctype="multipart/form-data" >
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-8">
                        <div class="card" style="min-height: 525px">
                            <div class="card-header">
                                <h4 class="card-title">Edit Produk</h4>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Nama Produk</label>
                                    <input type="text" name="name" class="form-control" value="{{ old('name') ? old('name') : $product->name }}">
                                    @error('name')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="description">Deskripsi</label>
                                  
                                    <!-- TAMBAHKAN ID YANG NNTINYA DIGUNAKAN UTK MENGHUBUNGKAN DENGAN CKEDITOR -->
                                    <textarea name="description" id="description" class="form-control">{{ old('description') ? old('description') : $product->description }}</textarea>
                                    @error('description')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card" style="min-height: 525px">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select name="status" class="form-control">
                                        <option value="1" {{ $product->status == '1' ? 'selected':'' }}>Publish</option>
                                        <option value="0" {{ $product->status == '0' ? 'selected':'' }}>Draft</option>
                                    </select>
                                    <p class="text-danger">{{ $errors->first('status') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="category_id">Kategori</label>
                                    
                                    <!-- DATA KATEGORI DIGUNAKAN DISINI, SEHINGGA SETIAP PRODUK USER BISA MEMILIH KATEGORINYA -->
                                    <select name="category_id" class="form-control">
                                        <option value="">Pilih</option>
                                        @foreach ($category as $row)
                                        <option value="{{ $row->id }}" {{ $product->category_id == $row->id ? 'selected':'' }}>{{ $row->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('category_id')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="price">Harga</label>
                                    <input type="number" name="price" class="form-control" value="{{ old('price') ? old('price') : $product->price }}">
                                    @error('price')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                  <label for="image">Foto Produk</label>
                                  <img src="{{asset('storage/images/product/'.$product->image)}}" class="img-thumbnail mb-2" alt="{{$product->name}}">
                                  <small class="text-info"><strong>biarkan kosong jika tidak ingin mengganti gambar</strong></small>
                                  <div class="custom-file">
                                    <input type="file" name="image" class="custom-file-input" id="customFile">
                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                  </div>
                                  @error('image')
                                        <small class="text-danger">{{$message}}</small>
                                    @enderror
                                </div>
                              </div>
                              <div class="card-footer bg-white">
                                <div class="form-group">
                                    <button type="button" data-toggle="modal" data-target="#modalDelete" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i> Delete</button>
                                    <button type="submit" class="btn float-right btn-primary btn-sm">Update Product</button>
                                </div>
                              </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</main>

{{-- Modal Delete --}}
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content container p-3">
      <div class="head d-flex align-item-center justify-content-end">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="body text-center">
        <div class="info mb-3">
          <i class="text-danger far fa-times-circle fa-5x my-5"></i>
          <h5>Apakah anda yakin ingin menghapus item ini?</h5>
          <h6>data yang telah dihapus tidak bisa dikembalikan</h6>
        </div>
        <form action="{{route('product.destroy', $product->id)}}" method="post" >
          @csrf
          @method('DELETE')
          <button type="button" data-dismiss="modal" class="btn btn-primary m-2">Cancel</button>
          <button type="submit" class="btn btn-danger m-2">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection

<!-- PADA ADMIN LAYOUTS, TERDAPAT YIELD JS YANG BERARTI KITA BISA MEMBUAT SECTION JS UNTUK MENAMBAHKAN SCRIPT JS JIKA DIPERLUKAN -->
@section('js')
    <!-- LOAD CKEDITOR -->
    {{-- <script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
    <script>
        //TERAPKAN CKEDITOR PADA TEXTAREA DENGAN ID DESCRIPTION
        CKEDITOR.replace('description', {
          height: 300
        });
    </script>
    <script type="application/javascript">
      $('input[type="file"]').change(function(e){
          var fileName = e.target.files[0].name;
          $('.custom-file-label').html(fileName);
      });
  </script> --}}
@endsection

resources/views/products/index.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin | Product</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">{{$active}}</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">List Product</h4>

                            <!-- BUAT TOMBOL UNTUK MENGARAHKAN KE HALAMAN ADD PRODUK -->
                            <a href="{{ route('product.create') }}"
                                class="btn btn-primary btn-sm float-right">Tambah</a>

                        </div>
                        <div class="card-body">
                            <!-- JIKA TERDAPAT FLASH SESSION, MAKA TAMPILAKAN -->
                            @if (session('success'))
                            <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            @if (session('error'))
                            <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif
                            <!-- JIKA TERDAPAT FLASH SESSION, MAKA TAMPILAKAN -->

                            <!-- BUAT FORM UNTUK PENCARIAN, METHODNYA ADALAH GET -->
                            <form action="{{ route('product.index') }}" method="get">
                                <div class="input-group mb-3 col-md-3 float-right">
                                    <!-- KEMUDIAN NAME-NYA ADALAH Q YANG AKAN MENAMPUNG DATA PENCARIAN -->
                                    <input type="text" name="q" class="form-control" placeholder="Cari..."
                                        value="{{ request()->q }}">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-secondary" type="button">Cari</button>
                                    </div>
                                </div>
                            </form>

                            <!-- TABLE UNTUK MENAMPILKAN DATA PRODUK -->
                            <div class="table-responsive">
                                <table class="table table-hover table-striped table-bordered">
                                    <thead class="thead-light">
                                        <tr>
                                            <th class="text-center" style="width: 80px">No.</th>
                                            <th class="text-center" style="width: 150px">Image</th>
                                            <th>Produk</th>
                                            <th class="text-center">Harga</th>
                                            <th class="text-center">Status</th>
                                            <th class="text-center">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!-- LOOPING DATA TERSEBUT MENGGUNAKAN FORELSE -->
                                        <!-- ADAPUN PENJELASAN ADA PADA ARTIKEL SEBELUMNYA -->
                                        @forelse ($product as $row)
                                        <tr>
                                            <td class="text-center align-middle">
                                                {{($product->currentPage() - 1) * $product->perPage () + $loop->iteration}}.
                                            </td>
                                            <td class="text-center">
                                                <img src="{{ asset('storage/images/product/' . $row->image) }}"
                                                    width="100px" height="100px" alt="{{ $row->name }}">
                                            </td>
                                            <td>
                                                <strong>{{ $row->name }}</strong><br>
                                                <!-- ADAPUN NAMA KATEGORINYA DIAMBIL DARI HASIL RELASI PRODUK DAN KATEGORI -->
                                                <h6>Kategori: <span
                                                        class="badge badge-info">{{ $row->category->name }}</span></h6>
                                            </td>
                                            <td class="text-center align-middle">Rp.{{ number_format($row->price) }}
                                            </td>

                                            <!-- KARENA BERISI HTML MAKA KITA GUNAKAN { !! UNTUK MENCETAK DATA -->
                                            <td class="text-center align-middle">{!! $row->status_label !!}</td>
                                            <td class="text-center align-middle">
                                                <a href="{{ route('product.edit', $row->id) }}"
                                                    class="btn btn-warning btn-sm">Edit</a>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="6" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                            <!-- MEMBUAT LINK PAGINASI JIKA ADA -->
                            {!! $product->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection